In [10]:
import numpy as np
arr = np.random.randn(5)
print(arr)
print(arr.shape)

[-1.54565314 -0.09134987 -0.13555835 -0.53940851 -1.8199218 ]
(5,)


In [2]:
print(arr.shape) #bad

(5,)


In [6]:
arr = arr.reshape(5,1) #good
print(arr)

[[ 2.16981033]
 [ 0.53822708]
 [ 0.8690854 ]
 [ 1.78055355]
 [-0.9582732 ]]


In [7]:
arr = np.random.randn(1,5)
print(arr)

[[-1.1164524   1.92710972  2.01618928 -0.44307715  1.76324174]]


In [9]:
print(arr.shape)

(1, 5)


In [14]:
a = np.random.randn(123,12)
b = np.random.randn(12,100)
c = np.dot(a,b)
print(c.shape)

(123, 100)


In [25]:
a = np.random.randn(1,3)
b = np.random.randn(1,3)
print(a,b,sep='\n')

[[-1.69664885  0.80891845  0.39050048]]
[[-0.56377961 -0.58813792 -0.55725591]]


In [24]:
c = np.dot(a,b)
print(c.shape)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [3]:
import numpy as np
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = np.dot(a,b)
print(c.shape)

(4, 2)


In [10]:
# GRADED FUNCTION: two_layer_model

def two_layer_model(X, Y, layers_dims, learning_rate = 0.0075, num_iterations = 3000, print_cost=False):
    """
    Implements a two-layer neural network: LINEAR->RELU->LINEAR->SIGMOID.
    
    Arguments:
    X -- input data, of shape (n_x, number of examples)
    Y -- true "label" vector (containing 1 if cat, 0 if non-cat), of shape (1, number of examples)
    layers_dims -- dimensions of the layers (n_x, n_h, n_y)
    num_iterations -- number of iterations of the optimization loop
    learning_rate -- learning rate of the gradient descent update rule
    print_cost -- If set to True, this will print the cost every 100 iterations 
    
    Returns:
    parameters -- a dictionary containing W1, W2, b1, and b2
    """
    
    np.random.seed(1)
    grads = {}
    costs = []                              # to keep track of the cost
    m = X.shape[1]                           # number of examples
    (n_x, n_h, n_y) = layers_dims
    
    # Initialize parameters dictionary, by calling one of the functions you'd previously implemented
    #(≈ 1 line of code)
    # parameters = ...
    # YOUR CODE STARTS HERE
    parameters = initialize_parameters(n_x, n_h, n_y)
    
    # YOUR CODE ENDS HERE
    
    # Get W1, b1, W2 and b2 from the dictionary parameters.
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    
    # Loop (gradient descent)

    for i in range(0, num_iterations):

        # Forward propagation: LINEAR -> RELU -> LINEAR -> SIGMOID. Inputs: "X, W1, b1, W2, b2". Output: "A1, cache1, A2, cache2".
        #(≈ 2 lines of code)
        A1, cache1 = linear_activation_forward(X, W1, b1, activation = 'relu')
        A2, cache2 = linear_activation_forward(A1, W2, b2, activation = 'sigmoid')
        # YOUR CODE STARTS HERE
        
        
        # YOUR CODE ENDS HERE
        
        # Compute cost
        #(≈ 1 line of code)
        # cost = ...
        # YOUR CODE STARTS HERE
        cost = compute_cost(A2,Y)
        
        # YOUR CODE ENDS HERE
        
        # Initializing backward propagation
        dA2 = - (np.divide(Y, A2) - np.divide(1 - Y, 1 - A2))
        
        # Backward propagation. Inputs: "dA2, cache2, cache1". Outputs: "dA1, dW2, db2; also dA0 (not used), dW1, db1".
        #(≈ 2 lines of code)
        dA1, dW2, db2 = linear_activation_backward(dA2, cache2, activation ='sigmoid')
        dA0, dW1, db1 = linear_activation_backward(dA1, cache1, activation ='relu')
        # YOUR CODE STARTS HERE
        
        
        # YOUR CODE ENDS HERE
        
        # Set grads['dWl'] to dW1, grads['db1'] to db1, grads['dW2'] to dW2, grads['db2'] to db2
        grads['dW1'] = dW1
        grads['db1'] = db1
        grads['dW2'] = dW2
        grads['db2'] = db2
        
        # Update parameters.
        #(approx. 1 line of code)
        parameters = update_parameters(parameters, grads, learning_rate)
        # YOUR CODE STARTS HERE
        
        
        # YOUR CODE ENDS HERE

        # Retrieve W1, b1, W2, b2 from parameters
        W1 = parameters["W1"]
        b1 = parameters["b1"]
        W2 = parameters["W2"]
        b2 = parameters["b2"]
        
        # Print the cost every 100 iterations
        if print_cost and i % 100 == 0 or i == num_iterations - 1:
            print("Cost after iteration {}: {}".format(i, np.squeeze(cost)))
        if i % 100 == 0 or i == num_iterations:
            costs.append(cost)

    return parameters, costs

def plot_costs(costs, learning_rate=0.0075):
    plt.plot(np.squeeze(costs))
    plt.ylabel('cost')
    plt.xlabel('iterations (per hundreds)')
    plt.title("Learning rate =" + str(learning_rate))
    plt.show()

In [11]:
c = a**2 + b.T**2 

In [9]:
d = a.T+b.T
print(d-c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
a = np.random.randn(8,1)
print(a.reshape(2,2,2))

[[[-0.16036013  1.37720394]
  [-0.77016933 -0.92530938]]

 [[-1.58922608  0.71791022]
  [ 0.64044397 -0.68016759]]]


In [33]:
print((9+16*2+4+36)**0.5)


9.0


In [32]:
print(56**0.5)

7.483314773547883


In [2]:
import numpy as np
x = np.random.randn(4,3)
print(np.sum(x, axis = 1,keepdims = True).shape)

(4, 1)
